/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhilai_opengllearn_GlTestView_GlTestRender */

#ifndef _Included_com_zhilai_opengllearn_GlTestView_GlTestRender
#define _Included_com_zhilai_opengllearn_GlTestView_GlTestRender
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
