/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhilai_opengllearn_GlTestView */

#ifndef _Included_com_zhilai_opengllearn_GlTestView
#define _Included_com_zhilai_opengllearn_GlTestView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhilai_opengllearn_GlTestView
 * Method:    renderOnSurCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhilai_opengllearn_GlTestView_renderOnSurCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_zhilai_opengllearn_GlTestView
 * Method:    renderOnSurChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhilai_opengllearn_GlTestView_renderOnSurChanged
  (JNIEnv *, jclass);

/*
 * Class:     com_zhilai_opengllearn_GlTestView
 * Method:    renderOnDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhilai_opengllearn_GlTestView_renderOnDrawFrame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
